version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: vocabulary-db
    environment:
      POSTGRES_DB: vocabulary_db
      POSTGRES_USER: vocabulary_user
      POSTGRES_PASSWORD: vocabulary_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - vocabulary-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vocabulary-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://vocabulary_user:vocabulary_password@database:5432/vocabulary_db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - vocabulary-network
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vocabulary-frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - vocabulary-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  vocabulary-network:
    driver: bridge