version: '3.8'

services:
  # Backend API (外部Supabaseプロジェクト利用)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vocabulary-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      # 以下はデプロイ先の環境（.env / CI secret）で上書き
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app:ro
    command: npm run start

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vocabulary-frontend
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:3001/api
      VITE_SUPABASE_URL: ${SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:ro
    depends_on:
      - backend
    command: npm run preview

networks: {}