version: '3.8'

services:
  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vocabulary_db_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password

  backend:
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://dev_user:dev_password@database:5432/vocabulary_db_dev
      DEBUG: "vocabulary:*"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules: